# Generated by Django 3.2.7 on 2021-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_path',
            new_name='posterpath',
        ),
    ]
