# Generated by Django 3.2.7 on 2021-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
