# Generated by Django 3.2.7 on 2021-10-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_actors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorMovies',
        ),
    ]
