# Generated by Django 3.2.7 on 2021-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_mam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='actors',
        ),
        migrations.DeleteModel(
            name='MAM',
        ),
    ]
